name: yaml2podo
version: 0.1.29
description: The `yaml2podo` is a generator and utility (all in one) that generates PODO classes to convert between JSON and Dart objects
homepage: https://github.com/mezoni/yaml2podo
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  args: ^1.6.0
  analyzer: ^0.40.4
  build: ^1.5.0
  dart_style: ^1.3.8
  path: ^1.7.0
  yaml: ^2.2.1
dev_dependencies:
  http: ^0.12.0+2
  pedantic: ^1.9.0
  test: ^1.6.3