name: yaml2podo
version: 0.1.31
description: The `yaml2podo` is a generator and utility (all in one) that generates PODO classes to convert between JSON and Dart objects
homepage: https://github.com/mezoni/yaml2podo
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  args: ^2.0.0-nullsafety.0
  #analyzer: ^0.41.1
  build: ^1.6.2
  #dart_style: ^1.3.10
  path: ^1.8.0
  yaml: ^3.0.0
dev_dependencies:
  http: ^0.12.0+2
  pedantic: ^1.10.0
  #test: ^1.16.0-nullsafety.19
